{% set name = "azure-mgmt-containerregistry" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: f2bcdbcf0b9fdc2df0df9eccb77cb489091d3c670ed53cba77e5ffd734e9539b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - azure-common >=1.1,<2
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0

test:
  imports:
    - azure.mgmt.containerregistry
    - azure.mgmt.containerregistry.v2017_03_01
    - azure.mgmt.containerregistry.v2017_03_01.models
    - azure.mgmt.containerregistry.v2017_03_01.operations
    - azure.mgmt.containerregistry.v2017_10_01
    - azure.mgmt.containerregistry.v2017_10_01.models
    - azure.mgmt.containerregistry.v2017_10_01.operations
    - azure.mgmt.containerregistry.v2018_02_01_preview
    - azure.mgmt.containerregistry.v2018_02_01_preview.models
    - azure.mgmt.containerregistry.v2018_02_01_preview.operations
    - azure.mgmt.containerregistry.v2018_09_01
    - azure.mgmt.containerregistry.v2018_09_01.models
    - azure.mgmt.containerregistry.v2018_09_01.operations

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Container Registry Client Library for Python

  doc_url: https://docs.microsoft.com/en-us/python/api/overview/azure/container-registry
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - andreyz4k
